export const FETCH_BOOK_LIST = 'FETCH_BOOK_LIST'

export const SET_BOOKID = 'SET_BOOKID'

export const SET_BOOKTITLE = 'SET_BOOKTITLE'

export const SET_BOOKPAGE = 'SET_BOOKPAGE'

export const SET_BOOKHEADER = 'SET_BOOKHEADER'

export const SET_BOOKTEXT = 'SET_BOOKTEXT'

export const SET_BOOKIMG = 'SET_BOOKIMG'

export const SET_GRAYSCALE = 'SET_GRAYSCALE'

export const SET_SEPIA = 'SET_SEPIA'

export const SET_SATURATE = 'SET_SATURATE'

export const SET_HUEROTATE = 'SET_HUEROTATE'

export const SET_INVERT = 'SET_INVERT'

export const SET_BRIGHTNESS = 'SET_BRIGHTNESS'

export const SET_CONTRAST = 'SET_CONTRAST'

export const SET_BLUR = 'SET_BLUR'

export const SET_POSTLINK = 'SET_POSTLINK'

export const SET_LIVESTREAMLINK = 'SET_LIVESTREAMLINK'

export const SET_VIDEOLINK = 'SET_VIDEOLINK'

export const PRIVACY = 'PRIVACY'